# S&P 500 tickers with company names for search
SP500 = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "AMZN": "Amazon.com Inc.",
    "NVDA": "NVIDIA Corporation",
    "GOOGL": "Alphabet Inc. Class A",
    "GOOG": "Alphabet Inc. Class C",
    "META": "Meta Platforms Inc.",
    "TSLA": "Tesla Inc.",
    "BRK.B": "Berkshire Hathaway Inc.",
    "UNH": "UnitedHealth Group Inc.",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase & Co.",
    "V": "Visa Inc.",
    "PG": "Procter & Gamble Co.",
    "XOM": "Exxon Mobil Corporation",
    "MA": "Mastercard Inc.",
    "HD": "Home Depot Inc.",
    "CVX": "Chevron Corporation",
    "MRK": "Merck & Co. Inc.",
    "ABBV": "AbbVie Inc.",
    "LLY": "Eli Lilly and Company",
    "PEP": "PepsiCo Inc.",
    "KO": "Coca-Cola Company",
    "COST": "Costco Wholesale Corporation",
    "AVGO": "Broadcom Inc.",
    "WMT": "Walmart Inc.",
    "MCD": "McDonald's Corporation",
    "CSCO": "Cisco Systems Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "ACN": "Accenture plc",
    "ABT": "Abbott Laboratories",
    "DHR": "Danaher Corporation",
    "NEE": "NextEra Energy Inc.",
    "LIN": "Linde plc",
    "ADBE": "Adobe Inc.",
    "NKE": "Nike Inc.",
    "ORCL": "Oracle Corporation",
    "CRM": "Salesforce Inc.",
    "AMD": "Advanced Micro Devices Inc.",
    "INTC": "Intel Corporation",
    "DIS": "Walt Disney Company",
    "VZ": "Verizon Communications Inc.",
    "CMCSA": "Comcast Corporation",
    "TXN": "Texas Instruments Inc.",
    "PM": "Philip Morris International Inc.",
    "WFC": "Wells Fargo & Company",
    "RTX": "RTX Corporation",
    "QCOM": "Qualcomm Inc.",
    "HON": "Honeywell International Inc.",
    "UNP": "Union Pacific Corporation",
    "IBM": "International Business Machines",
    "SPGI": "S&P Global Inc.",
    "CAT": "Caterpillar Inc.",
    "BA": "Boeing Company",
    "GE": "General Electric Company",
    "AMGN": "Amgen Inc.",
    "LOW": "Lowe's Companies Inc.",
    "DE": "Deere & Company",
    "INTU": "Intuit Inc.",
    "GS": "Goldman Sachs Group Inc.",
    "ELV": "Elevance Health Inc.",
    "AXP": "American Express Company",
    "BKNG": "Booking Holdings Inc.",
    "BLK": "BlackRock Inc.",
    "MDLZ": "Mondelez International Inc.",
    "ISRG": "Intuitive Surgical Inc.",
    "GILD": "Gilead Sciences Inc.",
    "ADI": "Analog Devices Inc.",
    "TJX": "TJX Companies Inc.",
    "SYK": "Stryker Corporation",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "VRTX": "Vertex Pharmaceuticals Inc.",
    "ADP": "Automatic Data Processing Inc.",
    "MMC": "Marsh & McLennan Companies Inc.",
    "SBUX": "Starbucks Corporation",
    "CVS": "CVS Health Corporation",
    "PLD": "Prologis Inc.",
    "LRCX": "Lam Research Corporation",
    "CI": "Cigna Group",
    "ETN": "Eaton Corporation plc",
    "SCHW": "Charles Schwab Corporation",
    "CB": "Chubb Limited",
    "MO": "Altria Group Inc.",
    "ZTS": "Zoetis Inc.",
    "SO": "Southern Company",
    "DUK": "Duke Energy Corporation",
    "BDX": "Becton Dickinson and Company",
    "TMUS": "T-Mobile US Inc.",
    "CME": "CME Group Inc.",
    "BSX": "Boston Scientific Corporation",
    "CL": "Colgate-Palmolive Company",
    "AON": "Aon plc",
    "ITW": "Illinois Tool Works Inc.",
    "EQIX": "Equinix Inc.",
    "MU": "Micron Technology Inc.",
    "PYPL": "PayPal Holdings Inc.",
    "SHW": "Sherwin-Williams Company",
    "NOC": "Northrop Grumman Corporation",
}

def search_tickers(query: str) -> list:
    """Search tickers by company name or symbol"""
    query = query.upper()
    results = []
    for ticker, name in SP500.items():
        if query in ticker or query in name.upper():
            results.append(f"{ticker} - {name}")
    return results[:10]  # Limit to 10 suggestions

def get_all_tickers() -> list:
    """Get all ticker symbols"""
    return list(SP500.keys())

def get_ticker_name(ticker: str) -> str:
    """Get company name for a ticker"""
    return SP500.get(ticker, ticker)
